config/routes.rb
Rails.application.routes.draw do
  post 'urls/new'

  get 'urls/edit'

  get 'urls/show'

  get 'urls/delete'

  get 'urls/update'

  get 'urls/index'

  get 'urls/destroy'

  get 'urls/short'

  root 'urls#index'

end

app/models/url.rb
class Url < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def new
    # byebug
    @url = Url.new(url_params)
    shortee = SecureRandom.hex(6)
    @url.short = "http://localhost:3000/#{shortee}"
    # byebug
    # respond_to do |format|
    #   if @url.save
    #     format.html { redirect_to urls_show_path, notice: 'Shortee was successfully created.' }
    #     format.json { render :show, status: :created, location: @url }
    #   else
    #     format.html { render :new }
    #     format.json { render json: @url.errors, status: :unprocessable_entity }
    #   end
    # end
    if @url.save
      # byebug
      # redirect_to action: "show", id: @url.id
      render "/urls/show"
    end
  end

  def edit
  end

  def show
  end

  def delete
  end

  def update
  end

  def index
  end

  def destroy
  end

  def short
    @url = Url.find_by_short(params)
  end

  private

  def url_params
    params.require(:url).permit(:long)
  end

  def generate_short_url
    self.short = SecureRandom.hex(6)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shortee</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/urls/_form.html.erb
<%= form_for Url.new, url: urls_new_path do |f| %>
  
  <div class="field">
    <%= f.label "Shorten URL" %><br>
    <%= f.text_field :long %>
  </div>
  <div class="actions">
    <%= f.submit "Shortee!"%>
  </div>
<% end %>

app/views/urls/delete.html.erb
<h1>Urls#delete</h1>
<p>Find me in app/views/urls/delete.html.erb</p>

app/views/urls/destroy.html.erb
<h1>Urls#destroy</h1>
<p>Find me in app/views/urls/destroy.html.erb</p>

app/views/urls/edit.html.erb
<h1>Urls#edit</h1>
<p>Find me in app/views/urls/edit.html.erb</p>

app/views/urls/index.html.erb
<h1>URL Shortener RAILS</h1>
<p>by JLoo</p>
<!DOCTYPE html>
<html>
<head>
  <title>Shortee</title>
</head>
<body>
	<%= render "/urls/form" %> 
</body>
</html>

app/views/urls/new.html.erb
<h1>Urls#new</h1>
<p>Find me in app/views/urls/new.html.erb</p>

app/views/urls/show.html.erb
<h1>Urls#show</h1>
<p>Find me in app/views/urls/show.html.erb</p>

<p id="notice"><%= notice %></p>

<p>
  <strong>Long URL:</strong>
  <%= @url.long %>
</p>
<p>
  <strong>Short URL:</strong>
  <%= @url.short %>
</p>

<%= link_to 'Back', urls_index_path %>

app/views/urls/update.html.erb
<h1>Urls#update</h1>
<p>Find me in app/views/urls/update.html.erb</p>